// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHZ6x3UrYrUfgedd6vMexgC_1n7xDGQUM',
    appId: '1:463853160761:web:d0629f1c315b24b2d100e8',
    messagingSenderId: '463853160761',
    projectId: 'pregnurture-f65cf',
    authDomain: 'pregnurture-f65cf.firebaseapp.com',
    storageBucket: 'pregnurture-f65cf.appspot.com',
    measurementId: 'G-PMM1RF0XVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCrx2ENli_ugwLvCtyNCC5RxYJGxm4AE0',
    appId: '1:463853160761:android:9d1aa02a9222d43cd100e8',
    messagingSenderId: '463853160761',
    projectId: 'pregnurture-f65cf',
    storageBucket: 'pregnurture-f65cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpjLWmYbMaCZ7Icu_QapsYaLLO9RKjKTg',
    appId: '1:463853160761:ios:0b898ad9f1d55a18d100e8',
    messagingSenderId: '463853160761',
    projectId: 'pregnurture-f65cf',
    storageBucket: 'pregnurture-f65cf.appspot.com',
    iosBundleId: 'com.example.pregNurture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpjLWmYbMaCZ7Icu_QapsYaLLO9RKjKTg',
    appId: '1:463853160761:ios:0b898ad9f1d55a18d100e8',
    messagingSenderId: '463853160761',
    projectId: 'pregnurture-f65cf',
    storageBucket: 'pregnurture-f65cf.appspot.com',
    iosBundleId: 'com.example.pregNurture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHZ6x3UrYrUfgedd6vMexgC_1n7xDGQUM',
    appId: '1:463853160761:web:08ddfcd3783a99e8d100e8',
    messagingSenderId: '463853160761',
    projectId: 'pregnurture-f65cf',
    authDomain: 'pregnurture-f65cf.firebaseapp.com',
    storageBucket: 'pregnurture-f65cf.appspot.com',
    measurementId: 'G-MP284LK9B7',
  );
}
